import { Product, Category } from './types';

export const categories: Category[] = [
  {
    id: 'sarees',
    slug: 'sarees',
    name: 'Sarees',
    image: 'https://images.pexels.com/photos/9398390/pexels-photo-9398390.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    subcategories: [
      { id: 'silk-sarees', slug: 'silk-sarees', name: 'Silk Sarees' },
      { id: 'cotton-sarees', slug: 'cotton-sarees', name: 'Cotton Sarees' },
      { id: 'designer-sarees', slug: 'designer-sarees', name: 'Designer Sarees' },
      { id: 'banarasi-sarees', slug: 'banarasi-sarees', name: 'Banarasi Sarees' },
      { id: 'organza-sarees', slug: 'organza-sarees', name: 'Organza Sarees' },
      { id: 'bridal-sarees', slug: 'bridal-sarees', name: 'Bridal Sarees' },
      { id: 'party-wear-sarees', slug: 'party-wear-sarees', name: 'Party Wear' },
    ],
  },
  {
    id: 'suits',
    slug: 'suits',
    name: 'Suits',
    image: 'https://images.pexels.com/photos/7275701/pexels-photo-7275701.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    subcategories: [
      { id: 'anarkali-suits', slug: 'anarkali-suits', name: 'Anarkali Suits' },
      { id: 'straight-suits', slug: 'straight-suits', name: 'Straight Suits' },
      { id: 'palazzo-suits', slug: 'palazzo-suits', name: 'Palazzo Suits' },
      { id: 'embroidered-sets', slug: 'embroidered-sets', name: 'Embroidered Sets' },
      { id: 'party-wear-sets', slug: 'party-wear-sets', name: 'Party Wear Sets' },
      { id: 'unstitched', slug: 'unstitched', name: 'Unstitched' },
    ],
  },
  {
    id: 'lehengas',
    slug: 'lehengas',
    name: 'Lehengas',
    image: 'https://images.pexels.com/photos/12062663/pexels-photo-12062663.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800',
    subcategories: [],
  },
  {
    id: 'kurtis-tunics',
    slug: 'kurtis-tunics',
    name: 'Kurtis & Tunics',
    image: 'https://images.pexels.com/photos/18194539/pexels-photo-18194539.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    subcategories: [],
  },
  {
    id: 'new-arrivals',
    slug: 'new-arrivals',
    name: 'New Arrivals',
    image: 'https://images.pexels.com/photos/34211603/pexels-photo-34211603.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200',
    subcategories: [],
  },
  {
    id: 'sale',
    slug: 'sale',
    name: 'Sale',
    image: 'https://images.pexels.com/photos/17876038/pexels-photo-17876038.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200',
    subcategories: [],
  },
];

const WHOLESALE_TIERS = [
  { minQty: 6, maxQty: 11, pricePerPiece: 0, label: '6–11 pcs' },
  { minQty: 12, maxQty: 23, pricePerPiece: 0, label: '12–23 pcs' },
  { minQty: 24, pricePerPiece: 0, label: '24+ pcs' },
];

function makeTiers(base: number): typeof WHOLESALE_TIERS {
  return [
    { minQty: 6, maxQty: 11, pricePerPiece: Math.round(base * 0.78), label: '6–11 pcs' },
    { minQty: 12, maxQty: 23, pricePerPiece: Math.round(base * 0.70), label: '12–23 pcs' },
    { minQty: 24, pricePerPiece: Math.round(base * 0.62), label: '24+ pcs' },
  ];
}

export const products: Product[] = [
  // SAREES
  {
    id: 'p1',
    slug: 'royal-banarasi-silk-saree',
    name: 'Royal Banarasi Silk Saree',
    category: 'sarees',
    subcategory: 'banarasi-sarees',
    images: [
      'https://images.pexels.com/photos/9398390/pexels-photo-9398390.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      'https://images.pexels.com/photos/20790059/pexels-photo-20790059.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800',
    ],
    fabric: 'Pure Katan Silk',
    careInstructions: 'Dry clean only. Store in a muslin cloth.',
    tags: ['bestseller', 'new'],
    description: 'A timeless Banarasi silk saree woven with intricate zari work. Perfect for weddings, pujas, and festive celebrations. Blouse piece included.',
    retailPrice: 8499,
    compareAtPrice: 10999,
    wholesalePricePerPiece: 6200,
    minOrderQty: 6,
    wholesaleTiers: makeTiers(6200),
  },
  {
    id: 'p2',
    slug: 'organza-floral-embroidery-saree',
    name: 'Organza Floral Embroidery Saree',
    category: 'sarees',
    subcategory: 'organza-sarees',
    images: [
      'https://images.pexels.com/photos/17468605/pexels-photo-17468605.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200',
      'https://images.pexels.com/photos/5872667/pexels-photo-5872667.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200',
    ],
    fabric: 'Organza with silk lining',
    careInstructions: 'Dry clean only. Avoid direct sunlight.',
    tags: ['new'],
    description: 'Ethereal organza saree adorned with hand-embroidered floral motifs in gold thread. Light, breathable, and effortlessly elegant for cocktail evenings.',
    retailPrice: 5999,
    wholesalePricePerPiece: 4200,
    minOrderQty: 6,
    wholesaleTiers: makeTiers(4200),
  },
  {
    id: 'p3',
    slug: 'pure-cotton-block-print-saree',
    name: 'Pure Cotton Block Print Saree',
    category: 'sarees',
    subcategory: 'cotton-sarees',
    images: [
      'https://images.pexels.com/photos/26969898/pexels-photo-26969898.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200',
      'https://images.pexels.com/photos/37442997/pexels-photo-37442997.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200',
    ],
    fabric: '100% Handloom Cotton',
    careInstructions: 'Hand wash in cold water. Do not wring.',
    tags: ['bestseller'],
    description: 'Authentic hand block-printed cotton saree from Rajasthan. Breathable, comfortable, and perfect for everyday elegance or casual gatherings.',
    retailPrice: 2499,
    compareAtPrice: 3199,
    wholesalePricePerPiece: 1750,
    minOrderQty: 6,
    wholesaleTiers: makeTiers(1750),
  },
  {
    id: 'p4',
    slug: 'bridal-silk-embroidered-saree',
    name: 'Bridal Embroidered Silk Saree',
    category: 'sarees',
    subcategory: 'bridal-sarees',
    images: [
      'https://images.pexels.com/photos/12579916/pexels-photo-12579916.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800',
      'https://images.pexels.com/photos/9398389/pexels-photo-9398389.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    ],
    fabric: 'Pure Silk with Zardozi',
    careInstructions: 'Dry clean only. Store flat.',
    tags: ['new'],
    description: 'Opulent bridal silk saree with heavy zardozi embroidery along the border and pallu. A celebration of tradition and luxury for your most special day.',
    retailPrice: 18999,
    wholesalePricePerPiece: 14500,
    minOrderQty: 6,
    wholesaleTiers: makeTiers(14500),
  },
  {
    id: 'p5',
    slug: 'designer-georgette-saree',
    name: 'Designer Georgette Party Saree',
    category: 'sarees',
    subcategory: 'designer-sarees',
    images: [
      'https://images.pexels.com/photos/17876038/pexels-photo-17876038.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200',
      'https://images.pexels.com/photos/34211603/pexels-photo-34211603.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200',
    ],
    fabric: 'Georgette with Sequin Work',
    careInstructions: 'Dry clean only.',
    tags: ['sale'],
    description: 'Glamorous georgette saree with all-over sequin embroidery. Perfect for parties, receptions, and cocktail dinners. Comes with matching blouse piece.',
    retailPrice: 4299,
    compareAtPrice: 6499,
    wholesalePricePerPiece: 2999,
    minOrderQty: 6,
    wholesaleTiers: makeTiers(2999),
  },
  // SUITS
  {
    id: 'p6',
    slug: 'anarkali-silk-suit-set',
    name: 'Anarkali Silk Suit Set',
    category: 'suits',
    subcategory: 'anarkali-suits',
    images: [
      'https://images.pexels.com/photos/18194533/pexels-photo-18194533.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      'https://images.pexels.com/photos/18194539/pexels-photo-18194539.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    ],
    fabric: 'Art Silk',
    careInstructions: 'Dry clean recommended.',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    tags: ['bestseller'],
    description: 'Floor-length anarkali suit in lustrous art silk with thread embroidery at the neckline. Paired with churidar and dupatta. Regal and effortlessly graceful.',
    retailPrice: 3799,
    wholesalePricePerPiece: 2650,
    minOrderQty: 6,
    wholesaleTiers: makeTiers(2650),
  },
  {
    id: 'p7',
    slug: 'palazzo-embroidered-suit',
    name: 'Palazzo Embroidered Suit',
    category: 'suits',
    subcategory: 'palazzo-suits',
    images: [
      'https://images.pexels.com/photos/7742859/pexels-photo-7742859.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      'https://images.pexels.com/photos/7275701/pexels-photo-7275701.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    ],
    fabric: 'Chiffon',
    careInstructions: 'Hand wash cold or dry clean.',
    sizes: ['S', 'M', 'L', 'XL'],
    tags: ['new'],
    description: 'Breezy chiffon palazzo suit with floral threadwork on the kurta. Wide-leg palazzo pants and printed dupatta included. Perfect for casual festivities.',
    retailPrice: 2899,
    compareAtPrice: 3499,
    wholesalePricePerPiece: 1999,
    minOrderQty: 6,
    wholesaleTiers: makeTiers(1999),
  },
  {
    id: 'p8',
    slug: 'straight-cut-embroidered-suit',
    name: 'Straight Cut Embroidered Suit',
    category: 'suits',
    subcategory: 'straight-suits',
    images: [
      'https://images.pexels.com/photos/20790061/pexels-photo-20790061.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800',
      'https://images.pexels.com/photos/20790059/pexels-photo-20790059.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800',
    ],
    fabric: 'Cotton Silk Blend',
    careInstructions: 'Machine wash gentle or dry clean.',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    tags: ['sale'],
    description: 'Elegant straight-cut suit with phulkari-inspired embroidery at the hem and cuffs. A timeless silhouette ideal for office-to-dinner transitions.',
    retailPrice: 2199,
    compareAtPrice: 2999,
    wholesalePricePerPiece: 1499,
    minOrderQty: 6,
    wholesaleTiers: makeTiers(1499),
  },
  {
    id: 'p9',
    slug: 'party-wear-embroidered-set',
    name: 'Party Wear Embroidered Set',
    category: 'suits',
    subcategory: 'party-wear-sets',
    images: [
      'https://images.pexels.com/photos/9398389/pexels-photo-9398389.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      'https://images.pexels.com/photos/12579916/pexels-photo-12579916.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800',
    ],
    fabric: 'Velvet & Net',
    careInstructions: 'Dry clean only.',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    tags: ['new', 'bestseller'],
    description: 'Luxurious velvet kurta with net palazzo and heavily embellished dupatta. This three-piece party set commands attention at every festive occasion.',
    retailPrice: 5499,
    wholesalePricePerPiece: 3900,
    minOrderQty: 6,
    wholesaleTiers: makeTiers(3900),
  },
  // LEHENGAS
  {
    id: 'p10',
    slug: 'bridal-lehenga-choli',
    name: 'Bridal Lehenga Choli Set',
    category: 'lehengas',
    subcategory: 'lehengas',
    images: [
      'https://images.pexels.com/photos/12062663/pexels-photo-12062663.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800',
      'https://images.pexels.com/photos/9398390/pexels-photo-9398390.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    ],
    fabric: 'Raw Silk with Zardozi',
    careInstructions: 'Dry clean only. Store in a breathable bag.',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'Custom'],
    tags: ['new', 'bestseller'],
    description: 'Exquisite bridal lehenga with dense zardozi embroidery on raw silk. The sweeping silhouette and intricate handwork make this a once-in-a-lifetime heirloom piece.',
    retailPrice: 24999,
    wholesalePricePerPiece: 19500,
    minOrderQty: 6,
    wholesaleTiers: makeTiers(19500),
  },
  {
    id: 'p11',
    slug: 'festive-mirror-work-lehenga',
    name: 'Festive Mirror Work Lehenga',
    category: 'lehengas',
    subcategory: 'lehengas',
    images: [
      'https://images.pexels.com/photos/18194533/pexels-photo-18194533.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      'https://images.pexels.com/photos/7742859/pexels-photo-7742859.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    ],
    fabric: 'Chaniya Silk',
    careInstructions: 'Dry clean only.',
    sizes: ['S', 'M', 'L', 'XL'],
    tags: ['sale'],
    description: 'Vibrant mirror-work lehenga with intricate hand-stitched shisha embellishments. Comes with a matching choli and embroidered dupatta for a complete festive look.',
    retailPrice: 8999,
    compareAtPrice: 12999,
    wholesalePricePerPiece: 6500,
    minOrderQty: 6,
    wholesaleTiers: makeTiers(6500),
  },
  // KURTIS & TUNICS
  {
    id: 'p12',
    slug: 'lucknowi-chikankari-kurti',
    name: 'Lucknowi Chikankari Kurti',
    category: 'kurtis-tunics',
    subcategory: 'kurtis-tunics',
    images: [
      'https://images.pexels.com/photos/37442997/pexels-photo-37442997.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200',
      'https://images.pexels.com/photos/26969898/pexels-photo-26969898.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200',
    ],
    fabric: 'Pure Cotton',
    careInstructions: 'Hand wash in cold water.',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    tags: ['bestseller'],
    description: 'Authentic Lucknowi chikankari kurti crafted by master artisans. The delicate shadow embroidery on pure cotton makes this a wardrobe essential for the discerning woman.',
    retailPrice: 1699,
    wholesalePricePerPiece: 1100,
    minOrderQty: 6,
    wholesaleTiers: makeTiers(1100),
  },
  {
    id: 'p13',
    slug: 'printed-rayon-tunic',
    name: 'Printed Rayon Tunic',
    category: 'kurtis-tunics',
    subcategory: 'kurtis-tunics',
    images: [
      'https://images.pexels.com/photos/17876038/pexels-photo-17876038.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200',
      'https://images.pexels.com/photos/34211603/pexels-photo-34211603.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200',
    ],
    fabric: 'Rayon',
    careInstructions: 'Machine wash cold, gentle cycle.',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    tags: ['new', 'sale'],
    description: 'Breezy rayon tunic with vibrant jaipuri floral print. Versatile enough to pair with leggings, palazzos, or jeans. A must-have everyday essential.',
    retailPrice: 899,
    compareAtPrice: 1299,
    wholesalePricePerPiece: 580,
    minOrderQty: 12,
    wholesaleTiers: makeTiers(580),
  },
  {
    id: 'p14',
    slug: 'embroidered-long-kurti',
    name: 'Embroidered Long Kurti',
    category: 'kurtis-tunics',
    subcategory: 'kurtis-tunics',
    images: [
      'https://images.pexels.com/photos/5872667/pexels-photo-5872667.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200',
      'https://images.pexels.com/photos/17468605/pexels-photo-17468605.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200',
    ],
    fabric: 'Cotton Blend',
    careInstructions: 'Hand wash recommended.',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    tags: ['new'],
    description: 'Long A-line kurti with intricate threadwork at the yoke and hem. The straight silhouette flatters all body types. Perfect for festivals and formal events.',
    retailPrice: 1299,
    wholesalePricePerPiece: 850,
    minOrderQty: 6,
    wholesaleTiers: makeTiers(850),
  },
  {
    id: 'p15',
    slug: 'silk-blend-anarkali-kurti',
    name: 'Silk Blend Anarkali Kurti',
    category: 'kurtis-tunics',
    subcategory: 'kurtis-tunics',
    images: [
      'https://images.pexels.com/photos/7275701/pexels-photo-7275701.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      'https://images.pexels.com/photos/18194539/pexels-photo-18194539.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    ],
    fabric: 'Silk Blend',
    careInstructions: 'Dry clean or hand wash cold.',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    tags: ['bestseller'],
    description: 'Flared anarkali-style kurti in rich silk blend with subtle shimmer. The flared hem adds drama and elegance, ideal for festive occasions paired with churidar.',
    retailPrice: 2199,
    compareAtPrice: 2799,
    wholesalePricePerPiece: 1550,
    minOrderQty: 6,
    wholesaleTiers: makeTiers(1550),
  },
  {
    id: 'p16',
    slug: 'designer-banarasi-party-saree',
    name: 'Designer Banarasi Party Saree',
    category: 'sarees',
    subcategory: 'party-wear-sarees',
    images: [
      'https://images.pexels.com/photos/20790061/pexels-photo-20790061.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800',
      'https://images.pexels.com/photos/12062663/pexels-photo-12062663.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800',
    ],
    fabric: 'Banarasi Brocade',
    careInstructions: 'Dry clean only.',
    tags: ['new', 'sale'],
    description: 'Stunning Banarasi brocade saree in deep jewel tones with a broad golden border. The signature woven motifs make each drape a work of art.',
    retailPrice: 6799,
    compareAtPrice: 8999,
    wholesalePricePerPiece: 4999,
    minOrderQty: 6,
    wholesaleTiers: makeTiers(4999),
  },
  {
    id: 'p17',
    slug: 'royal-velvet-lehenga',
    name: 'Royal Velvet Lehenga',
    category: 'lehengas',
    subcategory: 'lehengas',
    images: [
      'https://images.pexels.com/photos/9398389/pexels-photo-9398389.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      'https://images.pexels.com/photos/20790059/pexels-photo-20790059.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800',
    ],
    fabric: 'Velvet with Net',
    careInstructions: 'Dry clean only.',
    sizes: ['S', 'M', 'L', 'XL', 'Custom'],
    tags: ['new'],
    description: 'Rich royal blue velvet lehenga with gold sequin embroidery throughout. The heavily embellished choli and sheer dupatta complete a look fit for royalty.',
    retailPrice: 15999,
    wholesalePricePerPiece: 12500,
    minOrderQty: 6,
    wholesaleTiers: makeTiers(12500),
  },
  {
    id: 'p18',
    slug: 'chanderi-silk-saree',
    name: 'Chanderi Silk Saree',
    category: 'sarees',
    subcategory: 'silk-sarees',
    images: [
      'https://images.pexels.com/photos/5872667/pexels-photo-5872667.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200',
      'https://images.pexels.com/photos/26969898/pexels-photo-26969898.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200',
    ],
    fabric: 'Chanderi Silk',
    careInstructions: 'Dry clean only.',
    tags: ['bestseller'],
    description: 'Lightweight Chanderi silk saree with subtle zari buti across the body and a contrast border. Perfect for daytime events, pujas, and office parties.',
    retailPrice: 3999,
    wholesalePricePerPiece: 2800,
    minOrderQty: 6,
    wholesaleTiers: makeTiers(2800),
  },
];

export const heroImages = [
  {
    url: 'https://images.pexels.com/photos/34211603/pexels-photo-34211603.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200',
    headline: 'Timeless Ethnic.',
    subheadline: 'Timeless You.',
    cta: 'Explore Sarees',
    ctaLink: '/collections/sarees',
  },
  {
    url: 'https://images.pexels.com/photos/12062663/pexels-photo-12062663.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800',
    headline: 'Crafted for',
    subheadline: 'Every Celebration.',
    cta: 'Shop Lehengas',
    ctaLink: '/collections/lehengas',
  },
  {
    url: 'https://images.pexels.com/photos/26969898/pexels-photo-26969898.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200',
    headline: 'Elegance in',
    subheadline: 'Every Thread.',
    cta: 'New Arrivals',
    ctaLink: '/collections/new-arrivals',
  },
];

export function formatPrice(price: number): string {
  return new Intl.NumberFormat('en-IN', {
    style: 'currency',
    currency: 'INR',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(price);
}

export function getProductsByCategory(category: string): Product[] {
  return products.filter(p => p.category === category);
}

export function getProductsByTag(tag: string): Product[] {
  return products.filter(p => p.tags.includes(tag as 'new' | 'bestseller' | 'sale'));
}

export function getProductBySlug(slug: string): Product | undefined {
  return products.find(p => p.slug === slug);
}

export function getRelatedProducts(product: Product, limit = 4): Product[] {
  return products
    .filter(p => p.category === product.category && p.id !== product.id)
    .slice(0, limit);
}
